# Databricks Apps configuration for voc-hotel-app
# See https://docs.databricks.com/aws/en/dev-tools/databricks-apps/app-runtime
#
# DEPLOYMENT INSTRUCTIONS:
# 1. Update the values below to match your Databricks workspace
# 2. Store sensitive values (CLIENT_SECRET, GENIE_SPACE_ID) in Databricks Secrets
# 3. Reference secrets using ${SECRET_NAME} syntax
# 4. Deploy with: databricks apps deploy
#
# SECURITY NOTES:
# - Never commit actual secret values to version control
# - Use Databricks Secrets for DATABRICKS_CLIENT_SECRET and GENIE_SPACE_ID
# - Ensure service principal has required permissions:
#   * CAN USE on SQL Warehouse
#   * SELECT on Unity Catalog tables
#   * Access to Lakebase OLTP instance
#   * Access to Genie Space

command:
  - python
  - dash_app.py

env:
  # SQL Warehouse for Unity Catalog queries
  - name: DATABRICKS_SQL_WAREHOUSE_PATH
    # valueFrom: sql-warehouse
    value: /sql/1.0/warehouses/75fd8278393d07eb

  - name: DATABRICKS_SERVER_HOSTNAME
    value: e2-demo-west.cloud.databricks.com

  # Genie Space ID for AI queries
  - name: GENIE_SPACE_ID
    value: 01f0c8a5873a169b84ed013f2edbece0
  
  - name: DATABRICKS_CATALOG
    value: main
  - name: DATABRICKS_SCHEMA
    value: voc_demo
  - name: ISSUES_TABLE_NAME
    value: open_issues_diagnosis
  - name: REVIEWS_TABLE_NAME
    value: review_aspect_details
  - name: HOTELS_TABLE_NAME
    value: hotel_locations
  - name: RUNBOOK_TABLE_NAME
    value: aspect_runbook


  - name: DATABRICKS_OVERVIEW_DASHBOARD_URL
    value: https://e2-demo-west.cloud.databricks.com/embed/dashboardsv3/01f0c59e3622190a95124c8cdc691ac6?o=2556758628403379

  - name: DATABRICKS_PROPERTY_DASHBOARD_URL
    value: https://e2-demo-west.cloud.databricks.com/embed/dashboardsv3/01f0c5a0f3bb1f3f9d1eb328cdf78986?o=2556758628403379