# Databricks Apps configuration for voc-hotel-app
# See https://docs.databricks.com/aws/en/dev-tools/databricks-apps/app-runtime
#
# DEPLOYMENT INSTRUCTIONS:
# 1. Update the values below to match your Databricks workspace
# 2. Store sensitive values (CLIENT_SECRET, GENIE_SPACE_ID) in Databricks Secrets
# 3. Reference secrets using ${SECRET_NAME} syntax
# 4. Deploy with: databricks apps deploy
#
# SECURITY NOTES:
# - Never commit actual secret values to version control
# - Use Databricks Secrets for DATABRICKS_CLIENT_SECRET and GENIE_SPACE_ID
# - Ensure service principal has required permissions:
#   * CAN USE on SQL Warehouse
#   * SELECT on Unity Catalog tables
#   * Access to Lakebase OLTP instance
#   * Access to Genie Space

command:
  - python
  - dash_app.py

env:
  # SQL Warehouse for Unity Catalog queries
  - name: DATABRICKS_SQL_WAREHOUSE_PATH
    value: /sql/1.0/warehouses/a9fea331792bc9d6

  # Genie Space ID for AI queries
  - name: GENIE_SPACE_ID
    value: 01f0a933aa7a14dc8b377db69cd237ee
  
  # Lakebase OLTP database configuration
  - name: LAKEBASE_INSTANCE_NAME
    value: voc-app-demo
  
  - name: LAKEBASE_DB_NAME
    value: lakehouse_inn_db

